version: "3.7"

services:
  aleste-cv:
    container_name: aleste-cv
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
